
#define BB_GL_EXTERN

#include "gles20_windows.h"

//for wglGetProcAddress
#include <windows.h>

void bb_gles20_windows_init(){
	glActiveTexture=(void*)wglGetProcAddress("glActiveTexture");
	glAttachShader=(void*)wglGetProcAddress("glAttachShader");
	glBindAttribLocation=(void*)wglGetProcAddress("glBindAttribLocation");
	glBindBuffer=(void*)wglGetProcAddress("glBindBuffer");
	glBindFramebuffer=(void*)wglGetProcAddress("glBindFramebuffer");
	glBindRenderbuffer=(void*)wglGetProcAddress("glBindRenderbuffer");
	glBlendColor=(void*)wglGetProcAddress("glBlendColor");
	glBlendEquation=(void*)wglGetProcAddress("glBlendEquation");
	glBlendEquationSeparate=(void*)wglGetProcAddress("glBlendEquationSeparate");
	glBlendFuncSeparate=(void*)wglGetProcAddress("glBlendFuncSeparate");
	glBufferData=(void*)wglGetProcAddress("glBufferData");
	glBufferSubData=(void*)wglGetProcAddress("glBufferSubData");
	glCheckFramebufferStatus=(void*)wglGetProcAddress("glCheckFramebufferStatus");
	glClearDepthf=(void*)wglGetProcAddress("glClearDepthf");
	glCompileShader=(void*)wglGetProcAddress("glCompileShader");
	glCompressedTexImage2D=(void*)wglGetProcAddress("glCompressedTexImage2D");
	glCompressedTexSubImage2D=(void*)wglGetProcAddress("glCompressedTexSubImage2D");
	glCreateProgram=(void*)wglGetProcAddress("glCreateProgram");
	glCreateShader=(void*)wglGetProcAddress("glCreateShader");
	glDeleteBuffers=(void*)wglGetProcAddress("glDeleteBuffers");
	glDeleteFramebuffers=(void*)wglGetProcAddress("glDeleteFramebuffers");
	glDeleteProgram=(void*)wglGetProcAddress("glDeleteProgram");
	glDeleteRenderbuffers=(void*)wglGetProcAddress("glDeleteRenderbuffers");
	glDeleteShader=(void*)wglGetProcAddress("glDeleteShader");
	glDepthRangef=(void*)wglGetProcAddress("glDepthRangef");
	glDetachShader=(void*)wglGetProcAddress("glDetachShader");
	glDisableVertexAttribArray=(void*)wglGetProcAddress("glDisableVertexAttribArray");
	glEnableVertexAttribArray=(void*)wglGetProcAddress("glEnableVertexAttribArray");
	glFramebufferRenderbuffer=(void*)wglGetProcAddress("glFramebufferRenderbuffer");
	glFramebufferTexture2D=(void*)wglGetProcAddress("glFramebufferTexture2D");
	glGenBuffers=(void*)wglGetProcAddress("glGenBuffers");
	glGenerateMipmap=(void*)wglGetProcAddress("glGenerateMipmap");
	glGenFramebuffers=(void*)wglGetProcAddress("glGenFramebuffers");
	glGenRenderbuffers=(void*)wglGetProcAddress("glGenRenderbuffers");
	glGetActiveAttrib=(void*)wglGetProcAddress("glGetActiveAttrib");
	glGetActiveUniform=(void*)wglGetProcAddress("glGetActiveUniform");
	glGetAttachedShaders=(void*)wglGetProcAddress("glGetAttachedShaders");
	glGetAttribLocation=(void*)wglGetProcAddress("glGetAttribLocation");
	glGetBufferParameteriv=(void*)wglGetProcAddress("glGetBufferParameteriv");
	glGetFramebufferAttachmentParameteriv=(void*)wglGetProcAddress("glGetFramebufferAttachmentParameteriv");
	glGetProgramiv=(void*)wglGetProcAddress("glGetProgramiv");
	glGetProgramInfoLog=(void*)wglGetProcAddress("glGetProgramInfoLog");
	glGetRenderbufferParameteriv=(void*)wglGetProcAddress("glGetRenderbufferParameteriv");
	glGetShaderiv=(void*)wglGetProcAddress("glGetShaderiv");
	glGetShaderInfoLog=(void*)wglGetProcAddress("glGetShaderInfoLog");
	glGetShaderPrecisionFormat=(void*)wglGetProcAddress("glGetShaderPrecisionFormat");
	glGetShaderSource=(void*)wglGetProcAddress("glGetShaderSource");
	glGetUniformfv=(void*)wglGetProcAddress("glGetUniformfv");
	glGetUniformiv=(void*)wglGetProcAddress("glGetUniformiv");
	glGetUniformLocation=(void*)wglGetProcAddress("glGetUniformLocation");
	glGetVertexAttribfv=(void*)wglGetProcAddress("glGetVertexAttribfv");
	glGetVertexAttribiv=(void*)wglGetProcAddress("glGetVertexAttribiv");
	glGetVertexAttribPointerv=(void*)wglGetProcAddress("glGetVertexAttribPointerv");
	glIsBuffer=(void*)wglGetProcAddress("glIsBuffer");
	glIsFramebuffer=(void*)wglGetProcAddress("glIsFramebuffer");
	glIsProgram=(void*)wglGetProcAddress("glIsProgram");
	glIsRenderbuffer=(void*)wglGetProcAddress("glIsRenderbuffer");
	glIsShader=(void*)wglGetProcAddress("glIsShader");
	glLinkProgram=(void*)wglGetProcAddress("glLinkProgram");
	glReleaseShaderCompiler=(void*)wglGetProcAddress("glReleaseShaderCompiler");
	glRenderbufferStorage=(void*)wglGetProcAddress("glRenderbufferStorage");
	glSampleCoverage=(void*)wglGetProcAddress("glSampleCoverage");
	glShaderBinary=(void*)wglGetProcAddress("glShaderBinary");
	glShaderSource=(void*)wglGetProcAddress("glShaderSource");
	glStencilFuncSeparate=(void*)wglGetProcAddress("glStencilFuncSeparate");
	glStencilMaskSeparate=(void*)wglGetProcAddress("glStencilMaskSeparate");
	glStencilOpSeparate=(void*)wglGetProcAddress("glStencilOpSeparate");
	glUniform1f=(void*)wglGetProcAddress("glUniform1f");
	glUniform1fv=(void*)wglGetProcAddress("glUniform1fv");
	glUniform1i=(void*)wglGetProcAddress("glUniform1i");
	glUniform1iv=(void*)wglGetProcAddress("glUniform1iv");
	glUniform2f=(void*)wglGetProcAddress("glUniform2f");
	glUniform2fv=(void*)wglGetProcAddress("glUniform2fv");
	glUniform2i=(void*)wglGetProcAddress("glUniform2i");
	glUniform2iv=(void*)wglGetProcAddress("glUniform2iv");
	glUniform3f=(void*)wglGetProcAddress("glUniform3f");
	glUniform3fv=(void*)wglGetProcAddress("glUniform3fv");
	glUniform3i=(void*)wglGetProcAddress("glUniform3i");
	glUniform3iv=(void*)wglGetProcAddress("glUniform3iv");
	glUniform4f=(void*)wglGetProcAddress("glUniform4f");
	glUniform4fv=(void*)wglGetProcAddress("glUniform4fv");
	glUniform4i=(void*)wglGetProcAddress("glUniform4i");
	glUniform4iv=(void*)wglGetProcAddress("glUniform4iv");
	glUniformMatrix2fv=(void*)wglGetProcAddress("glUniformMatrix2fv");
	glUniformMatrix3fv=(void*)wglGetProcAddress("glUniformMatrix3fv");
	glUniformMatrix4fv=(void*)wglGetProcAddress("glUniformMatrix4fv");
	glUseProgram=(void*)wglGetProcAddress("glUseProgram");
	glValidateProgram=(void*)wglGetProcAddress("glValidateProgram");
	glVertexAttrib1f=(void*)wglGetProcAddress("glVertexAttrib1f");
	glVertexAttrib1fv=(void*)wglGetProcAddress("glVertexAttrib1fv");
	glVertexAttrib2f=(void*)wglGetProcAddress("glVertexAttrib2f");
	glVertexAttrib2fv=(void*)wglGetProcAddress("glVertexAttrib2fv");
	glVertexAttrib3f=(void*)wglGetProcAddress("glVertexAttrib3f");
	glVertexAttrib3fv=(void*)wglGetProcAddress("glVertexAttrib3fv");
	glVertexAttrib4f=(void*)wglGetProcAddress("glVertexAttrib4f");
	glVertexAttrib4fv=(void*)wglGetProcAddress("glVertexAttrib4fv");
	glVertexAttribPointer=(void*)wglGetProcAddress("glVertexAttribPointer");
}
